version: 2
linters-settings:
  lll:
    line-length: 120
    tab-width: 4
linters:
  enable:
    - lll           # limit line length
    - govet
    - revive
formatters:
  enable:
    - gofmt
    - gofumpt
